
name: pmemkv-other
on:
  schedule:
    # run this job at 01:00 UTC every second day
    - cron:  '0 1 */2 * *'

env:
  REPO:           pmemkv
  GITHUB_REPO:    pmem/pmemkv
  DOCKERHUB_REPO: pmem/pmemkv

jobs:
  linux:
    name: pmemkv-other
    runs-on: ubuntu-latest
    env:
      HOST_WORKDIR:   /home/runner/work/pmemkv/pmemkv
      WORKDIR:        utils/docker
      TYPE:           debug
    strategy:
      matrix:
        CONFIG: ["OS=centos OS_VER=8",
                 # XXX: clang-format-9 is missing
                 # "OS=archlinux-base OS_VER=latest",
                 "OS=debian OS_VER=testing",
                 "OS=debian OS_VER=unstable",
                 # XXX: clang-format-9 is missing
                 # "OS=fedora OS_VER=rawhide",
                 "OS=opensuse-leap OS_VER=latest",
                 "OS=opensuse-tumbleweed OS_VER=latest",
                 "OS=ubuntu OS_VER=rolling"]
    steps:
       - name: Print out the current date and time
         run: date

       - name: Clone the git repo
         uses: actions/checkout@v2
         with:
            fetch-depth: 50

       - name: Pull or rebuild the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh rebuild

       - name: Run the build
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build.sh
